### ISSUE TITLE
set zipcodeFieldName can not get special name

### ISSUE THREAD

**Issue by haha861924** [patw0929/react-twzipcode#10]
```
<TWzipcode 
      handleChangeCounty={onTWzipcodeChange}
      handleChangeDistrict={onTWzipcodeChange}
      zipcodeValue='110'
      zipcodeFieldName='zip'
      countyValue='台北市'
      countyFieldName='city'
      districtValue='信義區'
  />
```

I set zipcodeFieldName for 'zip', but my form can't find that name 
![image](https://user-images.githubusercontent.com/40877568/203098936-f5642b02-f99a-4df3-82c8-2ce290094006.png)

I would like to make a PR for this.

**Comment by patw0929** [comment]
Fixed in https://github.com/patw0929/react-twzipcode/pull/11 .
